# Site settings
remote_theme: chesterhow/tale
title:          Lisbon Revisited
description:    "Cenas"

url:            "https://pablu.github.io/lisbonrevisited"

# Author
author:
  name:         Ant√≥nio de Castro Caeiro
  url:          https://acaeiro.github.io/temas
  email:        pablodes@protonmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
